#!/bin/bash

outcard="hw:sndrpihifiberry"
incard="hw:CARD1"

#Need to do this to run as root
if [ ! -e /usr/lib/arm-linux-gnueabihf/jack ]; then
    ln -s /usr/local/lib/jack /usr/lib/arm-linux-gnueabihf/jack
fi
export LD_LIBRARY_PATH=/usr/local/lib

WD="$( cd "$(dirname "$0")" ; pwd -P )"
JACK_DRIVER_DIR=/usr/local/lib/jack

cd /home/pi/sc

export PATH=.:$PATH

export SC_JACK_DEFAULT_OUTPUTS="system"
export SC_JACK_DEFAULT_INPUTS="alsa_in:capture_1"

jackd -P75 -dalsa -d $outcard -p1024 -n3 &
alsa_in -d $incard -c1 -p1024 -n3 &
sleep 1
#./scsynth -u 57110 -a 116 -i 2 -o 2 -b 1026 -D 0 -R 0 -U plugins:share -C 0 -l 64

`sleep 10 && jack_connect alsa_in:capture_1 SuperCollider:in_1` &

#./scsynth -u 57110 -a 116 -i 2 -o 2 -b 1026 -R 0 -U plugins:share -C 0 -l 8
echo | xvfb-run --auto-servernum ./sclang -a -l sclang.yaml $WD/init.scd



#echo "" > $WD/sclang.log

