#!/bin/bash

PLAYCMD=/usr/bin/mplayer
ROOTDIR=`dirname $0`
ASSETDIR=$ROOTDIR/media

sleep 1

PLAYCMD="/usr/bin/mplayer -channels 8 -loop 0 -ao alsa:device=ttable "
$PLAYCMD $ROOTDIR/media/anna-8ch.flac
