#!/bin/bash

#Need to do this to run as root
if [ ! -e /usr/lib/arm-linux-gnueabihf/jack ]; then
    ln -s /usr/local/lib/jack /usr/lib/arm-linux-gnueabihf/jack
fi

WD="$( cd "$(dirname "$0")" ; pwd -P )"
JACK_DRIVER_DIR=/usr/local/lib/jack
export LD_LIBRARY_PATH=/usr/local/lib

cd /home/pi/sc

cd $WD
python button-osc.py &

cd /home/pi/sc
/usr/local/bin/jackd -P75 -dalsa -dhw:1 -p1024 -n3 -s &
xvfb-run --auto-servernum ./sclang -a -l ./sclang.yaml $WD/init.scd #&> sclang.log

